# Generated by Django 5.0.14 on 2026-10-05 22:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spring_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('block_tehsil', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(help_text='Elevation above MSL in meters')),
                ('spring_type', models.CharField(choices=[('Fracture', 'Fracture / Joint Spring'), ('Depression', 'Depression Spring'), ('Contact', 'Lithological Contact Spring'), ('Fault-controlled', 'Fault-controlled Spring'), ('Karst', 'Karst / Solution Spring')], default='Fracture', max_length=32)),
                ('geological_formation', models.CharField(max_length=255)),
                ('aquifer_type', models.CharField(choices=[('Unconfined Fractured Rock', 'Unconfined Fractured Rock'), ('Confined', 'Confined Aquifer'), ('Semi-confined Colluvium', 'Semi-confined Colluvium / Debris')], max_length=48)),
                ('strike_deg', models.FloatField(blank=True, help_text='Strike azimuth (0-360)', null=True)),
                ('dip_deg', models.FloatField(blank=True, help_text='Dip angle (0-90)', null=True)),
                ('dip_direction', models.CharField(blank=True, max_length=16)),
                ('average_discharge', models.FloatField(help_text='Annual Average Discharge (LPM)')),
                ('min_discharge', models.FloatField(help_text='Lean season minimum discharge (LPM)')),
                ('max_discharge', models.FloatField(help_text='Peak monsoon discharge (LPM)')),
                ('monsoon_discharge', models.FloatField(default=0.0)),
                ('summer_discharge', models.FloatField(default=0.0)),
                ('seasonality', models.CharField(default='Perennial', max_length=32)),
                ('status', models.CharField(choices=[('Active', 'Active & Stable'), ('Drying', 'Discharge Declining'), ('Critical', 'Severely Depleted'), ('Revived', 'Post-Intervention Revived')], default='Active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_springs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement_date', models.DateField(db_index=True)),
                ('discharge_lpm', models.FloatField(help_text='Discharge rate in Liters Per Minute')),
                ('season', models.CharField(max_length=32)),
                ('measurement_method', models.CharField(help_text='V-notch weir, bucket timing, electromagnetic flowmeter', max_length=64)),
                ('water_temperature_c', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('electrical_conductivity', models.FloatField(blank=True, help_text='µS/cm', null=True)),
                ('observer', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_records', to='springs.spring')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
    ]
